# Site settings
title: MINT
subtitle: Model INTegration
email:
description: Model Integration through Knowledge-Rich Data and Process Composition
baseurl: ""
url: "" # the base hostname & protocol for your site
author:
street_address:
city:
state:
zip_code:
country:
phone:

# Social settings
#500px_url:
#facebook_url:
#github_url:
#gitlab_url: https://gitlab.com/u/andrewbanchich
#googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
#instagram_url: https://instagram.com
#linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
#pinterest_url:
#slack_url:
#twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown
