# Site settings
title: MINT
subtitle: Model INTegration
email:
description: Model Integration through Knowledge-Rich Data and Process Composition
baseurl: ""
url: "" # the base hostname & protocol for your site
author:
street_address:
city:
state:
zip_code:
country:
phone:
include: ['_services']

# Build settings
markdown: kramdown

navigation:
- title: Home
  url: /index.html
- title: Overview
  url: /overview.html
- title: Services and Software
  url: /products.html
- title: Publications
  url: /publications.html
- title: Demos and Videos
  url: /demo.html
- title: Releases
  url: /releases.html
- title: Models
  url: /models.html
- title: Testbeds
  url: /testbeds.html
- title: Notebooks
  url: /notebooks.html
kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids:       true
  toc_levels:     1..4
